#SELECT BÁSICO#

SELECT * FROM usuarios;


#OPERADORE ARIMÉTICOS#
SELECT email, (4+5) as 'producto' FROM usuarios;

#MOSTRAR NOMBRES Y APELLIDOS DE LOS USUARIOS INGRESADOS EN UN DETERMINADO AÑO#
SELECT nombre,apellido FROM usuarios WHERE YEAR(fecha) = 2018;

#MOSTRAR NOMBRES Y APELLIDOS DE LOS USUARIOS INGRESADOS CUYA FECHA DE REGISTRO SEA != A 2018#
SELECT nombre,apellido FROM usuarios WHERE YEAR(fecha) != 2018;

#MOSTRAR email DE LOS USUARIOS QUE CONTENGAN UNA LETRA a EN SU APELLIDO Y QUE SU CONTRASEÑA SEA 
1234#
SELECT email FROM usuarios WHERE apellido LIKE '%a%' AND password = w123;  

#SACAR TODOS LOS REGISTROS CUYO AÑO DE INGRESO SEA IMPAR#

SELECT * FROM usuarios WHERE (YEAR(fecha) % 2) != 0;
#OTRA FORMA DE RESOLVER EL EJERCICIO ANTERIOR ES USANDO LA FUNCION MOD QUE ES EL MÓDULO OPERADOR#
SELECT * FROM usuarios WHERE MOD(YEAR(fecha),2)= 0;

#SACAR TODOS LOS REGISTROS DE LA TABLA USUARIOS CUYO NOMBRE TENGA MAS DE 5 LETRAS Y 
QUE SE HAYAN REGISTRADO ANTES DEL 2020, Y MOSTRAR EL NOMBRE EN MAYÚSCULA#

SELECT UPPER(nombre) AS 'nombre',apellido  FROM usuarios WHERE (LENGTH(nombre) > 4)  AND (YEAR(fecha) < 2020);
